---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: debian-7.8
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[application_nodejs::default]
    attributes:
